### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by nesstea** [Markcreator/warframe-acolyte#1]
Not sure what the cause of the problem is, but running your page consumes like 60% of my CPU usage. Running the latest version of Chrome and I have a Ryzen 7 1800x processor.

I affinity it to 1 core and the core runs 100%, but i don't lag anymore :)

**Comment by Markcreator** [comment]
Huh, that's strange. I have tested on a i5-4670k on multiple browsers, and was unable to to experience loads above 3% on the process. Are you using any extensions that could affect the page's functioning?
I would like to further explore the issue, though am not sure how to reproduce the problem.

**Comment by nesstea** [comment]
It must have been a recent version of Chrome. the problem disappeared.
