### ISSUE TITLE
notification shows literal escape sequence of single quote

### ISSUE THREAD

**Issue by LynxReborn** [Markcreator/warframe-acolyte#10]
As you can see in the attached screenshot the notification shows the literal escape sequence of `'`. This can be fixed by adding flow control to `escapeHTML` to not escape `dictionary["acolytelocationupdate"]`. 

![image](https://user-images.githubusercontent.com/37845513/74264888-c4c87900-4d01-11ea-9879-a531fd41a787.png)

(This issue was only tested on the new Microsoft Edge with chromium base. I don't know if it exists in other browsers too.)

**Comment by Markcreator** [comment]
Resolved on master branch. Thank you!
