### ISSUE TITLE
Add notification?

### ISSUE THREAD

**Issue by evanslify** [Markcreator/warframe-acolyte#5]
Was about to built a bot for this, but after a bit of github search and I ended up here.
It could be a huge help if there's notification, instead of sound only. 

See [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)

**Comment by Markcreator** [comment]
Thank you for your suggestion! I will see in the morning if I can implement it for you.

**Comment by Markcreator** [comment]
Notifications are now live!

**Comment by evanslify** [comment]
Thank you!
