### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by alexkoala** [Markcreator/warframe-acolyte#7]
Do you have a plan to support other languages like Korean?

[Here is the example Korean translation site](https://acolyte.ga) and [repository](https://github.com/acolyte-ko/warframe-acolyte/tree/korean).

**Comment by Markcreator** [comment]
Hey @AlexKoala ,
Thank you for sharing your awesome fork!

I really like this idea. I'm currently working on a patch that will allow everyone to easily contribute new languages.
I'll comment again when I've made some progress.

**Comment by Markcreator** [comment]
Hey @AlexKoala ,
I have now added support for adding new languages!
It is now possible to a new language JSON file to the 'lang' folder. See the existing JSON files for examples.
Everyone is free to PR new language files to the repository.

Have fun!
